/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author justi
 */

import java.util.Scanner;
import javax.swing.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.io.File;
import java.io.IOException;
import java.io.FileWriter;
import java.awt.Component;

public class SemesterProject extends javax.swing.JFrame {

    private String word;
    private int wordLength;
    private int lettersRemaining;
    private int score;
    private int gameGraphicNum;
    private int[] highScores = new int[5];
    private String[] highScorePlayers = new String[5];
    private File file = new File("highscores.txt");
    
    /**
     * Creates new form SemesterProject
     */
    public SemesterProject() {
        initComponents();
        readHighScores();
        showDate();
        showTime();
        ActionListener actionListener = new ActionListener() {
            public void actionPerformed (ActionEvent event) {
                returnMenu();
            }
        };
        Timer timer = new Timer(100, actionListener);
        timer.setRepeats(false);
        timer.setInitialDelay(3000);
        timer.start();
    }
    
     void showDate(){
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("MMMM dd, yyyy");
            dateLabel.setText(s.format(d));
    }
        
    void showTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                timeLabel.setText(s.format(d));
            }
        }).start();            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        startPanel = new javax.swing.JPanel();
        projectLabel = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        gameButton = new javax.swing.JButton();
        scoreButton = new javax.swing.JButton();
        creditsButton = new javax.swing.JButton();
        moonLabel = new javax.swing.JLabel();
        hangManPanel = new javax.swing.JPanel();
        hangManLabel = new javax.swing.JLabel();
        hangManBackButton = new javax.swing.JButton();
        hangManSkipButton = new javax.swing.JButton();
        aButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        fButton = new javax.swing.JButton();
        gButton = new javax.swing.JButton();
        hButton = new javax.swing.JButton();
        iButton = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        kButton = new javax.swing.JButton();
        lButton = new javax.swing.JButton();
        mButton = new javax.swing.JButton();
        nButton = new javax.swing.JButton();
        oButton = new javax.swing.JButton();
        pButton = new javax.swing.JButton();
        qButton = new javax.swing.JButton();
        rButton = new javax.swing.JButton();
        sButton = new javax.swing.JButton();
        tButton = new javax.swing.JButton();
        uButton = new javax.swing.JButton();
        vButton = new javax.swing.JButton();
        wButton = new javax.swing.JButton();
        xButton = new javax.swing.JButton();
        yButton = new javax.swing.JButton();
        zButton = new javax.swing.JButton();
        hangManScoreLabel = new javax.swing.JLabel();
        letter1Label = new javax.swing.JLabel();
        letter2Label = new javax.swing.JLabel();
        letter3Label = new javax.swing.JLabel();
        letter4Label = new javax.swing.JLabel();
        letter5Label = new javax.swing.JLabel();
        letter6Label = new javax.swing.JLabel();
        letter7Label = new javax.swing.JLabel();
        letter8Label = new javax.swing.JLabel();
        answerLabel = new javax.swing.JLabel();
        niceLabel = new javax.swing.JLabel();
        tryAgainLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        hangmanGraphicLabel = new javax.swing.JLabel();
        colorPanel = new javax.swing.JPanel();
        tempContinueButton = new javax.swing.JButton();
        colorLabel = new javax.swing.JLabel();
        scorePanel = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JLabel();
        scoreBackButton = new javax.swing.JButton();
        score1Label = new javax.swing.JLabel();
        score2Label = new javax.swing.JLabel();
        score3Label = new javax.swing.JLabel();
        score4Label = new javax.swing.JLabel();
        score5Label = new javax.swing.JLabel();
        creditsPanel = new javax.swing.JPanel();
        creditsLabel = new javax.swing.JLabel();
        creditsBackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gameOverPanel = new javax.swing.JPanel();
        gameOverLabel = new javax.swing.JLabel();
        gameOverEndButton = new javax.swing.JButton();
        finalScoreLabel = new javax.swing.JLabel();
        newHighScoreLabel = new javax.swing.JLabel();
        savePromptLabel = new javax.swing.JLabel();
        initialsPromptLabel = new javax.swing.JLabel();
        initialsTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JToggleButton();
        savedLabel = new javax.swing.JLabel();
        optionComboBox = new javax.swing.JComboBox<>();
        colorTestPanel = new javax.swing.JPanel();
        testColorLabel = new javax.swing.JLabel();
        redButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();
        purpleButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();
        randomButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        mainPanel.setLayout(new java.awt.CardLayout());

        startPanel.setBackground(new java.awt.Color(0, 0, 0));
        startPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        projectLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        projectLabel.setForeground(new java.awt.Color(255, 255, 255));
        projectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectLabel.setText("CS 2450 Semester Project Ver. 1.1");
        projectLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        groupLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        groupLabel.setForeground(new java.awt.Color(255, 255, 255));
        groupLabel.setText("By: To The Moon Studios");

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(groupLabel))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(projectLabel)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(projectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(groupLabel)
                .addGap(63, 63, 63))
        );

        mainPanel.add(startPanel, "startPanel");

        menuPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        menuLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("Menu");

        gameButton.setText("Play");
        gameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gameButtonMousePressed(evt);
            }
        });
        gameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameButtonActionPerformed(evt);
            }
        });

        scoreButton.setText("Highscores");
        scoreButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                scoreButtonMousePressed(evt);
            }
        });

        creditsButton.setText("Credits");
        creditsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                creditsButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(menuLabel))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(moonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(scoreButton)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(creditsButton)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(gameButton)
                        .addGap(69, 69, 69))))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(menuLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gameButton)
                        .addGap(18, 18, 18)
                        .addComponent(scoreButton))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moonLabel)))
                .addGap(18, 18, 18)
                .addComponent(creditsButton)
                .addGap(41, 41, 41))
        );

        mainPanel.add(menuPanel, "menuPanel");

        hangManPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        hangManLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        hangManLabel.setText("Hang Man");

        hangManBackButton.setText("Back");
        hangManBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hangManBackButtonMouseClicked(evt);
            }
        });

        hangManSkipButton.setText("Skip");
        hangManSkipButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hangManSkipButtonMouseClicked(evt);
            }
        });

        aButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        aButton.setText("A");
        aButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aButtonMouseClicked(evt);
            }
        });

        bButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        bButton.setText("B");
        bButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bButtonMouseClicked(evt);
            }
        });

        cButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        cButton.setText("C");
        cButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cButtonMouseClicked(evt);
            }
        });

        dButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        dButton.setText("D");
        dButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dButtonMouseClicked(evt);
            }
        });

        eButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        eButton.setText("E");
        eButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eButtonMouseClicked(evt);
            }
        });

        fButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        fButton.setText("F");
        fButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fButtonMouseClicked(evt);
            }
        });

        gButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        gButton.setText("G");
        gButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gButtonMouseClicked(evt);
            }
        });

        hButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        hButton.setText("H");
        hButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hButtonMouseClicked(evt);
            }
        });

        iButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        iButton.setText("I");
        iButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iButtonMouseClicked(evt);
            }
        });

        jButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton.setText("J");
        jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });

        kButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        kButton.setText("K");
        kButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButtonMouseClicked(evt);
            }
        });

        lButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lButton.setText("L");
        lButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lButtonMouseClicked(evt);
            }
        });

        mButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        mButton.setText("M");
        mButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mButtonMouseClicked(evt);
            }
        });

        nButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        nButton.setText("N");
        nButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nButtonMouseClicked(evt);
            }
        });

        oButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        oButton.setText("O");
        oButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oButtonMouseClicked(evt);
            }
        });

        pButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        pButton.setText("P");
        pButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pButtonMouseClicked(evt);
            }
        });

        qButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        qButton.setText("Q");
        qButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qButtonMouseClicked(evt);
            }
        });

        rButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        rButton.setText("R");
        rButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rButtonMouseClicked(evt);
            }
        });

        sButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        sButton.setText("S");
        sButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sButtonMouseClicked(evt);
            }
        });

        tButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        tButton.setText("T");
        tButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tButtonMouseClicked(evt);
            }
        });

        uButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        uButton.setText("U");
        uButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uButtonMouseClicked(evt);
            }
        });

        vButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        vButton.setText("V");
        vButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vButtonMouseClicked(evt);
            }
        });

        wButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        wButton.setText("W");
        wButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wButtonMouseClicked(evt);
            }
        });

        xButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        xButton.setText("X");
        xButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xButtonMouseClicked(evt);
            }
        });

        yButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        yButton.setText("Y");
        yButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yButtonMouseClicked(evt);
            }
        });

        zButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        zButton.setText("Z");
        zButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zButtonMouseClicked(evt);
            }
        });

        hangManScoreLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        hangManScoreLabel.setText("Score: 100");

        letter1Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter1Label.setText(" ___");

        letter2Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter2Label.setText("___");

        letter3Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter3Label.setText("___");

        letter4Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter4Label.setText("___");

        letter5Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter5Label.setText("___");

        letter6Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter6Label.setText("___");

        letter7Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter7Label.setText("___");

        letter8Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter8Label.setText("___");

        answerLabel.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        answerLabel.setText("ANSWER:");

        niceLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        niceLabel.setForeground(new java.awt.Color(0, 204, 51));
        niceLabel.setText("Nice!");

        tryAgainLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tryAgainLabel.setForeground(new java.awt.Color(255, 51, 51));
        tryAgainLabel.setText("Try Again!");

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dateLabel.setText("Date");

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        timeLabel.setText("Time");

        hangmanGraphicLabel.setPreferredSize(new java.awt.Dimension(80, 120));

        javax.swing.GroupLayout hangManPanelLayout = new javax.swing.GroupLayout(hangManPanel);
        hangManPanel.setLayout(hangManPanelLayout);
        hangManPanelLayout.setHorizontalGroup(
            hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hangManPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hangManPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qButton)
                        .addGap(107, 107, 107))
                    .addGroup(hangManPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(hangManPanelLayout.createSequentialGroup()
                                .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, hangManPanelLayout.createSequentialGroup()
                                        .addComponent(rButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(uButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(vButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(wButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(xButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(yButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(zButton))
                                    .addGroup(hangManPanelLayout.createSequentialGroup()
                                        .addComponent(aButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(hangManPanelLayout.createSequentialGroup()
                                                .addComponent(bButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(eButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(gButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(hButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(iButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(hangManPanelLayout.createSequentialGroup()
                                                .addComponent(answerLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(letter1Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(hangManPanelLayout.createSequentialGroup()
                                                        .addComponent(letter2Label)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(letter3Label)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(letter4Label))
                                                    .addComponent(hangmanGraphicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(letter5Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(letter6Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(letter7Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(letter8Label)))))
                                .addGap(23, 23, 23)
                                .addComponent(hangManSkipButton))
                            .addGroup(hangManPanelLayout.createSequentialGroup()
                                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(hangManPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hangManPanelLayout.createSequentialGroup()
                        .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hangManBackButton)
                            .addComponent(hangManScoreLabel)
                            .addComponent(niceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hangManLabel)
                        .addGap(209, 209, 209))
                    .addGroup(hangManPanelLayout.createSequentialGroup()
                        .addComponent(tryAgainLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        hangManPanelLayout.setVerticalGroup(
            hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hangManPanelLayout.createSequentialGroup()
                .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(hangManPanelLayout.createSequentialGroup()
                        .addComponent(hangManBackButton)
                        .addGap(18, 18, 18)
                        .addComponent(hangManScoreLabel)
                        .addGap(18, 18, 18)
                        .addComponent(niceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tryAgainLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(hangManPanelLayout.createSequentialGroup()
                        .addComponent(hangManLabel)
                        .addGap(18, 18, 18)
                        .addComponent(hangmanGraphicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letter1Label)
                    .addComponent(letter2Label)
                    .addComponent(letter3Label)
                    .addComponent(letter4Label)
                    .addComponent(letter5Label)
                    .addComponent(letter6Label)
                    .addComponent(letter7Label)
                    .addComponent(letter8Label)
                    .addComponent(answerLabel)
                    .addComponent(hangManSkipButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hangManPanelLayout.createSequentialGroup()
                        .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aButton)
                            .addComponent(bButton)
                            .addComponent(cButton)
                            .addComponent(dButton)
                            .addComponent(eButton)
                            .addComponent(fButton)
                            .addComponent(gButton)
                            .addComponent(hButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton)
                            .addComponent(kButton)
                            .addComponent(lButton)
                            .addComponent(mButton)
                            .addComponent(nButton)
                            .addComponent(oButton)
                            .addComponent(pButton)
                            .addComponent(qButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hangManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rButton)
                            .addComponent(sButton)
                            .addComponent(tButton)
                            .addComponent(uButton)
                            .addComponent(vButton)
                            .addComponent(wButton)
                            .addComponent(xButton)
                            .addComponent(yButton)
                            .addComponent(zButton)))
                    .addComponent(iButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        mainPanel.add(hangManPanel, "gamePanel");

        tempContinueButton.setText("temp Continue");
        tempContinueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tempContinueButtonMouseClicked(evt);
            }
        });
        tempContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempContinueButtonActionPerformed(evt);
            }
        });

        colorLabel.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        colorLabel.setText("Color");

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanelLayout.createSequentialGroup()
                .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorPanelLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(tempContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(colorPanelLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(colorLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(colorLabel)
                .addGap(113, 113, 113)
                .addComponent(tempContinueButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(colorPanel, "card8");

        scorePanel.setPreferredSize(new java.awt.Dimension(600, 400));

        scoreLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        scoreLabel.setText("Highscores");

        scoreBackButton.setText("Back");
        scoreBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scoreBackButtonMouseClicked(evt);
            }
        });

        score1Label.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        score1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score1Label.setText("ABC.....00000");

        score2Label.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        score2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score2Label.setText("ABC.....00000");

        score3Label.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        score3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score3Label.setText("ABC.....00000");

        score4Label.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        score4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score4Label.setText("ABC.....00000");

        score5Label.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        score5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score5Label.setText("ABC.....00000");

        javax.swing.GroupLayout scorePanelLayout = new javax.swing.GroupLayout(scorePanel);
        scorePanel.setLayout(scorePanelLayout);
        scorePanelLayout.setHorizontalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(scoreBackButton))
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(score1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(score2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(score3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(score4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(score5Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scorePanelLayout.setVerticalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(scoreLabel)
                .addGap(41, 41, 41)
                .addComponent(score1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(score2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(score3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(score4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(score5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scoreBackButton)
                .addGap(33, 33, 33))
        );

        mainPanel.add(scorePanel, "scorePanel");

        creditsPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        creditsLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        creditsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditsLabel.setText("Credits");

        creditsBackButton.setText("Back");
        creditsBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsBackButtonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Justin Ho, 014574794");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Brandon Moya, 014186939");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ishan Dhaliwal, 01330497");

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("David Tran, 011813529");

        javax.swing.GroupLayout creditsPanelLayout = new javax.swing.GroupLayout(creditsPanel);
        creditsPanel.setLayout(creditsPanelLayout);
        creditsPanelLayout.setHorizontalGroup(
            creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(creditsBackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(210, 210, 210))
        );
        creditsPanelLayout.setVerticalGroup(
            creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(creditsLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(creditsBackButton)
                .addGap(32, 32, 32))
        );

        mainPanel.add(creditsPanel, "creditsPanel");

        gameOverPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        gameOverLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        gameOverLabel.setText("Game Over!");

        gameOverEndButton.setText("End");
        gameOverEndButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gameOverEndButtonMousePressed(evt);
            }
        });

        finalScoreLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        finalScoreLabel.setText("Score: 100");

        newHighScoreLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        newHighScoreLabel.setText("You got a new high score!");

        savePromptLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        savePromptLabel.setText("Would you like to save your score in our records?");

        initialsPromptLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        initialsPromptLabel.setText("Please enter your initials:");

        initialsTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        initialsTextField.setText("ABC");

        saveButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        saveButton.setText("Save");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saveButtonMousePressed(evt);
            }
        });

        savedLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        savedLabel.setForeground(new java.awt.Color(0, 204, 0));
        savedLabel.setText("Saved!");

        optionComboBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        optionComboBox.setMaximumRowCount(2);
        optionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        optionComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                optionComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout gameOverPanelLayout = new javax.swing.GroupLayout(gameOverPanel);
        gameOverPanel.setLayout(gameOverPanelLayout);
        gameOverPanelLayout.setHorizontalGroup(
            gameOverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameOverPanelLayout.createSequentialGroup()
                .addGroup(gameOverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameOverPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(gameOverEndButton))
                    .addGroup(gameOverPanelLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(finalScoreLabel))
                    .addGroup(gameOverPanelLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(gameOverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newHighScoreLabel)
                            .addComponent(gameOverLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameOverPanelLayout.createSequentialGroup()
                .addGap(0, 112, Short.MAX_VALUE)
                .addGroup(gameOverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameOverPanelLayout.createSequentialGroup()
                        .addGroup(gameOverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gameOverPanelLayout.createSequentialGroup()
                                .addComponent(initialsPromptLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(initialsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveButton)
                                .addGap(14, 14, 14)
                                .addComponent(savedLabel))
                            .addComponent(savePromptLabel))
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameOverPanelLayout.createSequentialGroup()
                        .addComponent(optionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276))))
        );
        gameOverPanelLayout.setVerticalGroup(
            gameOverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameOverPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(gameOverLabel)
                .addGap(60, 60, 60)
                .addComponent(finalScoreLabel)
                .addGap(16, 16, 16)
                .addComponent(newHighScoreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savePromptLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gameOverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initialsPromptLabel)
                    .addComponent(initialsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savedLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(gameOverEndButton)
                .addGap(34, 34, 34))
        );

        mainPanel.add(gameOverPanel, "gameOverPanel");

        colorTestPanel.setPreferredSize(new java.awt.Dimension(600, 400));
        colorTestPanel.setLayout(null);

        testColorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testColorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        testColorLabel.setText("COLOR");
        colorTestPanel.add(testColorLabel);
        testColorLabel.setBounds(270, 20, 69, 51);

        redButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Brandon\\Documents\\NetBeansProjects\\SemesterProject1\\src\\main\\java\\ButtonImages\\button_round_red_resized.png")); // NOI18N
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });
        colorTestPanel.add(redButton);
        redButton.setBounds(20, 10, 100, 100);

        blueButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Brandon\\Documents\\NetBeansProjects\\SemesterProject1\\src\\main\\java\\ButtonImages\\button_round_blue_resized.png")); // NOI18N
        colorTestPanel.add(blueButton);
        blueButton.setBounds(20, 230, 100, 100);

        greenButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Brandon\\Documents\\NetBeansProjects\\SemesterProject1\\src\\main\\java\\ButtonImages\\button_round_green_resized.png")); // NOI18N
        colorTestPanel.add(greenButton);
        greenButton.setBounds(130, 230, 100, 100);

        purpleButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Brandon\\Documents\\NetBeansProjects\\SemesterProject1\\src\\main\\java\\ButtonImages\\button_round_purple_resized.png")); // NOI18N
        purpleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purpleButtonActionPerformed(evt);
            }
        });
        colorTestPanel.add(purpleButton);
        purpleButton.setBounds(20, 120, 100, 100);

        yellowButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Brandon\\Documents\\NetBeansProjects\\SemesterProject1\\src\\main\\java\\ButtonImages\\button_round_yellow_resized.png")); // NOI18N
        colorTestPanel.add(yellowButton);
        yellowButton.setBounds(130, 120, 100, 100);

        randomButton.setText("RANDOMIZE!");
        randomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomButtonActionPerformed(evt);
            }
        });
        colorTestPanel.add(randomButton);
        randomButton.setBounds(460, 10, 100, 40);

        mainPanel.add(colorTestPanel, "card9");
        colorTestPanel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gameButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameButtonMousePressed
        mainPanel.removeAll();
        mainPanel.add(hangManPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        score = 100;
        hangManScoreLabel.setText("Score: " + score);
        gameGraphicNum = 1;
        updateHangmanGraphic();
        
        word = wordSelect();
        wordLength = word.length();
        lettersRemaining = wordLength;
        
        letter1Label.setText("___");
        letter2Label.setText("___");
        letter3Label.setText("___");
        letter4Label.setText("___");
        letter5Label.setText("___");
        letter6Label.setText("___");
        letter7Label.setText("___");
        letter8Label.setText("___");
        letter6Label.setVisible(true);
        letter7Label.setVisible(true);
        letter8Label.setVisible(true);
        if (wordLength == 5) {
            letter6Label.setVisible(false);
            letter7Label.setVisible(false);
            letter8Label.setVisible(false);
        }
        
        niceLabel.setVisible(false);
        tryAgainLabel.setVisible(false);
        
        aButton.setEnabled(true);
        bButton.setEnabled(true);
        cButton.setEnabled(true);
        dButton.setEnabled(true);
        eButton.setEnabled(true);
        fButton.setEnabled(true);
        gButton.setEnabled(true);
        hButton.setEnabled(true);
        iButton.setEnabled(true);
        jButton.setEnabled(true);
        kButton.setEnabled(true);
        lButton.setEnabled(true);
        mButton.setEnabled(true);
        nButton.setEnabled(true);
        oButton.setEnabled(true);
        pButton.setEnabled(true);
        qButton.setEnabled(true);
        rButton.setEnabled(true);
        sButton.setEnabled(true);
        tButton.setEnabled(true);
        uButton.setEnabled(true);
        vButton.setEnabled(true);
        wButton.setEnabled(true);
        xButton.setEnabled(true);
        yButton.setEnabled(true);
        zButton.setEnabled(true);
    }//GEN-LAST:event_gameButtonMousePressed

    private void scoreButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoreButtonMousePressed
        mainPanel.removeAll();
        updateHighScores();
        mainPanel.add(scorePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_scoreButtonMousePressed

    private void creditsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsButtonMousePressed
        mainPanel.removeAll();
        mainPanel.add(creditsPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_creditsButtonMousePressed

    private void hangManBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hangManBackButtonMouseClicked
        returnMenu();
    }//GEN-LAST:event_hangManBackButtonMouseClicked

    private void scoreBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoreBackButtonMouseClicked
        returnMenu();
    }//GEN-LAST:event_scoreBackButtonMouseClicked

    private void creditsBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsBackButtonMouseClicked
        returnMenu();
    }//GEN-LAST:event_creditsBackButtonMouseClicked

    private void gameOverEndButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameOverEndButtonMousePressed
        returnMenu();
    }//GEN-LAST:event_gameOverEndButtonMousePressed

    private void hangManSkipButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hangManSkipButtonMouseClicked
        score = 0;
        startColorGame();
    }//GEN-LAST:event_hangManSkipButtonMouseClicked

    private void aButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aButtonMouseClicked
        letterSelected(aButton);
    }//GEN-LAST:event_aButtonMouseClicked

    private void bButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bButtonMouseClicked
        letterSelected(bButton);
    }//GEN-LAST:event_bButtonMouseClicked

    private void cButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cButtonMouseClicked
        letterSelected(cButton);
    }//GEN-LAST:event_cButtonMouseClicked

    private void dButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dButtonMouseClicked
        letterSelected(dButton);
    }//GEN-LAST:event_dButtonMouseClicked

    private void eButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eButtonMouseClicked
        letterSelected(eButton);
    }//GEN-LAST:event_eButtonMouseClicked

    private void fButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fButtonMouseClicked
        letterSelected(fButton);
    }//GEN-LAST:event_fButtonMouseClicked

    private void gButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gButtonMouseClicked
        letterSelected(gButton);
    }//GEN-LAST:event_gButtonMouseClicked

    private void hButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hButtonMouseClicked
        letterSelected(hButton);
    }//GEN-LAST:event_hButtonMouseClicked

    private void iButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iButtonMouseClicked
        letterSelected(iButton);
    }//GEN-LAST:event_iButtonMouseClicked

    private void jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseClicked
        letterSelected(jButton);
    }//GEN-LAST:event_jButtonMouseClicked

    private void kButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButtonMouseClicked
        letterSelected(kButton);
    }//GEN-LAST:event_kButtonMouseClicked

    private void lButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lButtonMouseClicked
        letterSelected(lButton);
    }//GEN-LAST:event_lButtonMouseClicked

    private void mButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButtonMouseClicked
        letterSelected(mButton);
    }//GEN-LAST:event_mButtonMouseClicked

    private void nButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nButtonMouseClicked
        letterSelected(nButton);
    }//GEN-LAST:event_nButtonMouseClicked

    private void oButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oButtonMouseClicked
        letterSelected(oButton);
    }//GEN-LAST:event_oButtonMouseClicked

    private void pButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButtonMouseClicked
        letterSelected(pButton);
    }//GEN-LAST:event_pButtonMouseClicked

    private void qButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qButtonMouseClicked
        letterSelected(qButton);
    }//GEN-LAST:event_qButtonMouseClicked

    private void rButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rButtonMouseClicked
        letterSelected(rButton);
    }//GEN-LAST:event_rButtonMouseClicked

    private void sButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sButtonMouseClicked
        letterSelected(sButton);
    }//GEN-LAST:event_sButtonMouseClicked

    private void tButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tButtonMouseClicked
        letterSelected(tButton);
    }//GEN-LAST:event_tButtonMouseClicked

    private void uButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uButtonMouseClicked
        letterSelected(uButton);
    }//GEN-LAST:event_uButtonMouseClicked

    private void vButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vButtonMouseClicked
        letterSelected(vButton);
    }//GEN-LAST:event_vButtonMouseClicked

    private void wButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wButtonMouseClicked
        letterSelected(wButton);
    }//GEN-LAST:event_wButtonMouseClicked

    private void xButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xButtonMouseClicked
        letterSelected(xButton);
    }//GEN-LAST:event_xButtonMouseClicked

    private void yButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yButtonMouseClicked
        letterSelected(yButton);
    }//GEN-LAST:event_yButtonMouseClicked

    private void zButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zButtonMouseClicked
        letterSelected(zButton);
    }//GEN-LAST:event_zButtonMouseClicked

    private void tempContinueButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempContinueButtonMouseClicked
        mainPanel.removeAll();
        mainPanel.add(colorTestPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        shuffleButtons();
    }//GEN-LAST:event_tempContinueButtonMouseClicked

    private void optionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_optionComboBoxItemStateChanged
        String optionSelected = (String) optionComboBox.getSelectedItem();
        if (optionSelected.equalsIgnoreCase("Yes")) {
            initialsPromptLabel.setVisible(true);
            initialsTextField.setVisible(true);
            saveButton.setVisible(true);
        }
        else {
            initialsPromptLabel.setVisible(false);
            initialsTextField.setVisible(false);
            saveButton.setVisible(false);
        }
    }//GEN-LAST:event_optionComboBoxItemStateChanged

    private void saveButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMousePressed
        if (saveButton.isEnabled()) {
            saveButton.setEnabled(false);
            savedLabel.setVisible(true);
            addHighScores(score, initialsTextField.getText());
        }
    }//GEN-LAST:event_saveButtonMousePressed

    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redButtonActionPerformed

    private void tempContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempContinueButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempContinueButtonActionPerformed

    private void gameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameButtonActionPerformed

    private void purpleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purpleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purpleButtonActionPerformed

    private void randomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomButtonActionPerformed
        shuffleButtons();    
    }//GEN-LAST:event_randomButtonActionPerformed

    private void letterSelected(javax.swing.JButton button) {
        boolean letterFound = false;
        if (button.isEnabled())
            for (int i = 0; i < word.length(); i++) {
                String letter = String.valueOf(word.charAt(i));
                if (letter.equalsIgnoreCase(button.getText())) {
                    displayLetter(i, letter.toUpperCase());
                    lettersRemaining--;
                    letterFound = true;
                }
            }
        if (!letterFound && button.isEnabled()) {
            score -= 10;
            hangManScoreLabel.setText("Score: " + score);
            tryAgainLabel.setVisible(true);
            niceLabel.setVisible(false);
            gameGraphicNum++;
            updateHangmanGraphic();
        }
        if (score == 40)
            startColorGame();
        if (lettersRemaining == 0)
            startColorGame();
        button.setEnabled(false);
    }
    
    private void displayLetter(int index, String letter) {
        if (index == 0)
            letter1Label.setText(" " + letter + " ");
        if (index == 1)
            letter2Label.setText(" " + letter + " ");
        if (index == 2)
            letter3Label.setText(" " + letter + " ");
        if (index == 3)
            letter4Label.setText(" " + letter + " ");
        if (index == 4)
            letter5Label.setText(" " + letter + " ");
        if (index == 5)
            letter6Label.setText(" " + letter + " ");
        if (index == 6)
            letter7Label.setText(" " + letter + " ");
        if (index == 7)
            letter8Label.setText(" " + letter + " ");
        niceLabel.setVisible(true);
        tryAgainLabel.setVisible(false);
    }
    
    private void gameOverDisplay() {
        mainPanel.removeAll();
        mainPanel.add(gameOverPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        newHighScoreLabel.setVisible(false);
        savePromptLabel.setVisible(false);
        optionComboBox.setVisible(false);
        initialsPromptLabel.setVisible(false);
        initialsTextField.setVisible(false);
        saveButton.setVisible(false);
        savedLabel.setVisible(false);
        
        optionComboBox.setSelectedItem("No");
        saveButton.setEnabled(true);
        
        if (score > highScores[4]) {
            newHighScoreLabel.setVisible(true);
            savePromptLabel.setVisible(true);
            optionComboBox.setVisible(true);
        }
                
        finalScoreLabel.setText("Score: " + score);
    }
    
    private void returnMenu() {
        mainPanel.removeAll();
        mainPanel.add(menuPanel);
        moonLabel.setIcon(new ImageIcon(getClass().getResource("moon.png")));
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    
    private String wordSelect() {
        Random rand = new Random();
        String[] wordList = {"abstract", "cemetery", "nurse", "pharmacy", "climbing"};
        return wordList[rand.nextInt(5)];
    }
    
    
    private void updateHangmanGraphic() {
        if (gameGraphicNum == 1)
            hangmanGraphicLabel.setIcon(new ImageIcon(getClass().getResource("hangman1.JPG")));
        if (gameGraphicNum == 2)
            hangmanGraphicLabel.setIcon(new ImageIcon(getClass().getResource("hangman2.JPG")));
        if (gameGraphicNum == 3)
            hangmanGraphicLabel.setIcon(new ImageIcon(getClass().getResource("hangman3.JPG")));
        if (gameGraphicNum == 4)
            hangmanGraphicLabel.setIcon(new ImageIcon(getClass().getResource("hangman4.JPG")));
        if (gameGraphicNum == 5)
            hangmanGraphicLabel.setIcon(new ImageIcon(getClass().getResource("hangman5.JPG")));
        if (gameGraphicNum == 6)
            hangmanGraphicLabel.setIcon(new ImageIcon(getClass().getResource("hangman6.JPG")));
        if (gameGraphicNum == 7)
            hangmanGraphicLabel.setIcon(new ImageIcon(getClass().getResource("hangman7.JPG")));
    }
    
    private void startColorGame() {
        mainPanel.removeAll();
        mainPanel.add(colorPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    
    private void readHighScores() {
        try {
            Scanner scan = new Scanner(file);
            for (int i = 0; i < 5; i++) {
                highScorePlayers[i] = scan.next();
                highScores[i] = scan.nextInt();
            }
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void updateHighScores() {
        score1Label.setText(highScorePlayers[0] + " " + highScores[0]);
        score2Label.setText(highScorePlayers[1] + " " + highScores[1]);
        score3Label.setText(highScorePlayers[2] + " " + highScores[2]);
        score4Label.setText(highScorePlayers[3] + " " + highScores[3]);
        score5Label.setText(highScorePlayers[4] + " " + highScores[4]);
    }
    
    private void addHighScores(int newScore, String playerInitials) {
        int position;
        if (newScore > highScores[3]) {
            if (newScore > highScores[2]) {
                if (newScore > highScores[1]) {
                    if (newScore > highScores[0]) {
                        position = 0;
                    }
                    else
                        position = 1;
                }
                else
                    position = 2;
            }
            else
                position = 3;
        }
        else 
            position = 4;
        pushScores(newScore, playerInitials, position);
        saveHighScores();
    }
    
    private void saveHighScores() {
        try {
            FileWriter writer = new FileWriter(file);
            for (int i = 0; i < 5; i++) {
                writer.write(highScorePlayers[i]);
                writer.write(" ");
                writer.write(String.valueOf(highScores[i]));
                writer.write(" ");
            }
            writer.close();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void pushScores(int newScore, String playerInitials, int position) {
        for (int i = 4; i > position; i--) {
            highScorePlayers[i] = highScorePlayers[i - 1];
            highScores[i] = highScores[i - 1];
        }
        highScorePlayers[position] = playerInitials;
        highScores[position] = newScore;
    }
    
    private boolean intersectsComponent(Component component, Component[] components) {
        for (Component c : components) {
            if (c.getBounds().intersects(component.getBounds())) {
                return true;
            }
        }
        return false;
    }
    
    private void shuffleButtons() {
        Random spaceRand = new Random();
        
        redButton.setBounds(spaceRand.nextInt(colorTestPanel.getWidth() - 100), spaceRand.nextInt(colorTestPanel.getHeight() - 100), 100, 100);
        blueButton.setBounds(spaceRand.nextInt(colorTestPanel.getWidth() - 100), spaceRand.nextInt(colorTestPanel.getHeight() - 100), 100, 100);
        yellowButton.setBounds(spaceRand.nextInt(colorTestPanel.getWidth() - 100), spaceRand.nextInt(colorTestPanel.getHeight() - 100), 100, 100);
        greenButton.setBounds(spaceRand.nextInt(colorTestPanel.getWidth() - 100), spaceRand.nextInt(colorTestPanel.getHeight() - 100), 100, 100);
        purpleButton.setBounds(spaceRand.nextInt(colorTestPanel.getWidth() - 100), spaceRand.nextInt(colorTestPanel.getHeight() - 100), 100, 100);
        
        for (int tries = 0; tries < 100; tries++) {
            if (intersectsComponent(redButton, colorTestPanel.getComponents())) {
                redButton.setBounds(spaceRand.nextInt(colorTestPanel.getWidth() - 100), spaceRand.nextInt(colorTestPanel.getHeight() - 100), 100, 100);
            } else {
                colorTestPanel.add(redButton);
                break;
            }
        }
        
        for (int tries = 0; tries < 100; tries++) {
            if (intersectsComponent(blueButton, colorTestPanel.getComponents())) {
                blueButton.setBounds(spaceRand.nextInt(colorTestPanel.getWidth() - 100), spaceRand.nextInt(colorTestPanel.getHeight() - 100), 100, 100);
            } else {
                colorTestPanel.add(blueButton);
                break;
            }
        }
        
        for (int tries = 0; tries < 100; tries++) {
            if (intersectsComponent(yellowButton, colorTestPanel.getComponents())) {
                yellowButton.setBounds(spaceRand.nextInt(colorTestPanel.getWidth() - 100), spaceRand.nextInt(colorTestPanel.getHeight() - 100), 100, 100);
            } else {
                colorTestPanel.add(yellowButton);
                break;
            }
        }
        
        for (int tries = 0; tries < 100; tries++) {
            if (intersectsComponent(greenButton, colorTestPanel.getComponents())) {
                greenButton.setBounds(spaceRand.nextInt(colorTestPanel.getWidth() - 100), spaceRand.nextInt(colorTestPanel.getHeight() - 100), 100, 100);
            } else {
                colorTestPanel.add(greenButton);
                break;
            }
        }
        
        for (int tries = 0; tries < 100; tries++) {
            if (intersectsComponent(purpleButton, colorTestPanel.getComponents())) {
                purpleButton.setBounds(spaceRand.nextInt(colorTestPanel.getWidth() - 100), spaceRand.nextInt(colorTestPanel.getHeight() - 100), 100, 100);
            } else {
                colorTestPanel.add(redButton);
                break;
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SemesterProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SemesterProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SemesterProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SemesterProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SemesterProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aButton;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JButton bButton;
    private javax.swing.JButton blueButton;
    private javax.swing.JButton cButton;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JPanel colorTestPanel;
    private javax.swing.JButton creditsBackButton;
    private javax.swing.JButton creditsButton;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JPanel creditsPanel;
    private javax.swing.JButton dButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton eButton;
    private javax.swing.JButton fButton;
    private javax.swing.JLabel finalScoreLabel;
    private javax.swing.JButton gButton;
    private javax.swing.JButton gameButton;
    private javax.swing.JButton gameOverEndButton;
    private javax.swing.JLabel gameOverLabel;
    private javax.swing.JPanel gameOverPanel;
    private javax.swing.JButton greenButton;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JButton hButton;
    private javax.swing.JButton hangManBackButton;
    private javax.swing.JLabel hangManLabel;
    private javax.swing.JPanel hangManPanel;
    private javax.swing.JLabel hangManScoreLabel;
    private javax.swing.JButton hangManSkipButton;
    private javax.swing.JLabel hangmanGraphicLabel;
    private javax.swing.JButton iButton;
    private javax.swing.JLabel initialsPromptLabel;
    private javax.swing.JTextField initialsTextField;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton kButton;
    private javax.swing.JButton lButton;
    private javax.swing.JLabel letter1Label;
    private javax.swing.JLabel letter2Label;
    private javax.swing.JLabel letter3Label;
    private javax.swing.JLabel letter4Label;
    private javax.swing.JLabel letter5Label;
    private javax.swing.JLabel letter6Label;
    private javax.swing.JLabel letter7Label;
    private javax.swing.JLabel letter8Label;
    private javax.swing.JButton mButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel moonLabel;
    private javax.swing.JButton nButton;
    private javax.swing.JLabel newHighScoreLabel;
    private javax.swing.JLabel niceLabel;
    private javax.swing.JButton oButton;
    private javax.swing.JComboBox<String> optionComboBox;
    private javax.swing.JButton pButton;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JButton purpleButton;
    private javax.swing.JButton qButton;
    private javax.swing.JButton rButton;
    private javax.swing.JButton randomButton;
    private javax.swing.JButton redButton;
    private javax.swing.JButton sButton;
    private javax.swing.JToggleButton saveButton;
    private javax.swing.JLabel savePromptLabel;
    private javax.swing.JLabel savedLabel;
    private javax.swing.JLabel score1Label;
    private javax.swing.JLabel score2Label;
    private javax.swing.JLabel score3Label;
    private javax.swing.JLabel score4Label;
    private javax.swing.JLabel score5Label;
    private javax.swing.JButton scoreBackButton;
    private javax.swing.JButton scoreButton;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JPanel startPanel;
    private javax.swing.JButton tButton;
    private javax.swing.JButton tempContinueButton;
    private javax.swing.JLabel testColorLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel tryAgainLabel;
    private javax.swing.JButton uButton;
    private javax.swing.JButton vButton;
    private javax.swing.JButton wButton;
    private javax.swing.JButton xButton;
    private javax.swing.JButton yButton;
    private javax.swing.JButton yellowButton;
    private javax.swing.JButton zButton;
    // End of variables declaration//GEN-END:variables
}
